USE db_gest_mais;

DROP PROCEDURE IF EXISTS VERIFICAR_LOGIN;

DELIMITER $$
CREATE PROCEDURE VERIFICAR_LOGIN(
	IN USUARIO VARCHAR(8),
    IN SENHA VARCHAR(30)
)
BEGIN
	SELECT USU.CD_USUARIO AS cdUsuario, 
		USU.CD_PESSOA AS cdPessoa, 
        UE.CD_EMPRESA AS cdEmpresa, 
        PAUX.NOME AS nome, 
        PEMP.NOME AS nomeEmpresa,
        GROUP_CONCAT(FS.CD_FUNCAO SEPARATOR '|') AS cdFuncao 
	FROM USUARIO AS USU
    LEFT JOIN USUARIO_EMPRESA AS UE ON UE.CD_USUARIO = USU.CD_USUARIO
    LEFT JOIN PESSOA_AUX AS PAUX ON PAUX.CD_PESSOA = USU.CD_PESSOA AND PAUX.CD_EMPRESA = UE.CD_EMPRESA
    LEFT JOIN PESSOA_AUX AS PEMP ON PEMP.CD_PESSOA = UE.CD_EMPRESA AND PEMP.CD_EMPRESA = UE.CD_EMPRESA
    LEFT JOIN PERFIL_ACESSO AS PA ON PA.CD_PERFIL = UE.CD_PERFIL 
    LEFT JOIN FUNCOES_PERFIL AS FP ON FP.CD_PERFIL = PA.CD_PERFIL
    LEFT JOIN FUNCOES_SISTEMA AS FS ON FS.CD_FUNCAO = FP.CD_FUNCAO
    
    WHERE USU.CD_USUARIO = USUARIO AND USU.SENHA = SENHA AND USU.ATIVO
		AND UE.ATIVO 
        AND PAUX.ATIVO
        AND PA.ATIVO
        AND FS.ATIVO
        
	GROUP BY 
		USU.CD_USUARIO,
		USU.CD_PESSOA,
		UE.CD_EMPRESA,
		PAUX.NOME;

	/* SELECT 
    
    RIGHT JOIN USUARIO_EMPRESA AS UE ON UE.CD_PERFIL = PA.CD_PERFIL
    RIGHT JOIN USUARIO AS US ON US.CD_USUARIO = UE.CD_USUARIO
    WHERE FS.ATIVO = '1' AND US.ATIVO = '1' AND US.CD_USUARIO = USUARIO AND US.SENHA = SENHA;
	*/
END 
$$ DELIMITER ;