DROP DATABASE IF EXISTS DB_GEST_MAIS;
CREATE DATABASE DB_GEST_MAIS;
USE DB_GEST_MAIS;

-- Criação da tabela Pessoa
CREATE TABLE PESSOA (
    CD_PESSOA INT PRIMARY KEY AUTO_INCREMENT,
    TP_PESSOA CHAR(1) NOT NULL COMMENT '(F / J)',
    CPF_CNPJ CHAR(14),
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME
);

CREATE TABLE PESSOA_AUX (
    CD_PESSOA INT,
    CD_EMPRESA INT NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    DT_NASC DATE,
    RG CHAR(12),
    EMAIL VARCHAR(60) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    CLIENTE TINYINT(1) COMMENT '(S / N)',
    EMPRESA TINYINT(1) COMMENT '(S / N)',
    IMAGEM VARCHAR(100),
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME,

    PRIMARY KEY (CD_PESSOA, CD_EMPRESA),
    FOREIGN KEY (CD_EMPRESA) REFERENCES PESSOA (CD_PESSOA)
);

-- Criação da tabela Perfil de Acesso
CREATE TABLE PERFIL_ACESSO (
    CD_PERFIL INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PERFIL CHAR(20) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME
);

-- Criação da tabela Funções do Sistema
CREATE TABLE FUNCOES_SISTEMA (
    CD_FUNCAO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FUNCAO CHAR(30) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME
);

-- Criação da tabela Funções do Perfil
CREATE TABLE FUNCOES_PERFIL (
    CD_PERFIL INT NOT NULL,
    CD_FUNCAO INT NOT NULL,
    DT_HR_ALTERACAO DATETIME,
    PRIMARY KEY (CD_PERFIL, CD_FUNCAO),
    FOREIGN KEY (CD_PERFIL) REFERENCES PERFIL_ACESSO (CD_PERFIL),
    FOREIGN KEY (CD_FUNCAO) REFERENCES FUNCOES_SISTEMA (CD_FUNCAO)
);

-- Criação da tabela Usuário
CREATE TABLE USUARIO (
    CD_USUARIO CHAR(8) PRIMARY KEY,
    CD_PESSOA INT NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    SENHA CHAR(30) NOT NULL,
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME,
    FOREIGN KEY (CD_PESSOA) REFERENCES PESSOA (CD_PESSOA)
);

-- Criação da tabela Usuário por Empresa
CREATE TABLE USUARIO_EMPRESA (
    CD_USUARIO CHAR(8) NOT NULL,
    CD_EMPRESA INT NOT NULL,
    DT_VALID DATE,
    CD_PERFIL INT NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME,
    PRIMARY KEY (CD_USUARIO, CD_EMPRESA),
    FOREIGN KEY (CD_USUARIO) REFERENCES USUARIO (CD_USUARIO),
    FOREIGN KEY (CD_EMPRESA) REFERENCES PESSOA (CD_PESSOA)
);

-- Criação da tabela Cliente por Empresa
CREATE TABLE CLIENTE_EMPRESA (
    CD_CLIENTE INT NOT NULL,
    CD_EMPRESA INT NOT NULL,
    DT_INICIO DATE NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME,
    PRIMARY KEY (CD_CLIENTE, CD_EMPRESA),
    FOREIGN KEY (CD_CLIENTE) REFERENCES PESSOA (CD_PESSOA),
    FOREIGN KEY (CD_EMPRESA) REFERENCES PESSOA (CD_PESSOA)
);

-- Criação da tabela Cargo
CREATE TABLE CARGO (
    CD_CARGO INT PRIMARY KEY AUTO_INCREMENT,
    DESC_CARGO CHAR(30) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME
);

-- Criação da tabela Funcionário Cliente
CREATE TABLE FUNCIONARIO_CLIENTE (
    CD_FUNCIONARIO INT NOT NULL,
    CD_EMPRESA INT NOT NULL,
    CD_CLIENTE INT NOT NULL,
    DT_INICIO DATE NOT NULL,
    CARGO_FUNCIONARIO INT NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME,

    PRIMARY KEY (CD_FUNCIONARIO, CD_CLIENTE, CD_EMPRESA),
    FOREIGN KEY (CD_EMPRESA) REFERENCES PESSOA (CD_PESSOA),
    FOREIGN KEY (CD_FUNCIONARIO) REFERENCES PESSOA (CD_PESSOA),
    FOREIGN KEY (CD_CLIENTE) REFERENCES CLIENTE_EMPRESA (CD_CLIENTE),
    FOREIGN KEY (CARGO_FUNCIONARIO) REFERENCES CARGO (CD_CARGO)
);

-- Criação da tabela Situação Projeto
CREATE TABLE SITUACAO_PROJ (
    CD_SITUACAO INT PRIMARY KEY AUTO_INCREMENT,
    DESC_SITUACAO CHAR(20) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    ATIVIDADE TINYINT(1) NOT NULL COMMENT '(S / N)',
    COR CHAR(9),
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME
);

-- Criação da tabela Projeto
CREATE TABLE PROJETO (
    CD_PROJ INT PRIMARY KEY AUTO_INCREMENT,
    CD_EMPRESA INT NOT NULL,
    CD_CLIENTE INT NOT NULL,
    ID_PROJ_INTERNO CHAR(20) NOT NULL,
    ID_PROJ_CLIENTE CHAR(20),
    TP_PROJ CHAR(1) NOT NULL COMMENT '(A / P)',
    NOME_PROJ CHAR(40) NOT NULL,
    CD_RESP_PROJ INT NOT NULL,
    DT_INICIO_AVALIACAO DATE NOT NULL,
    DT_INICIO_NEGOCIACAO DATE,
    DT_INICIO_PREVISTA DATE NOT NULL,
    DT_FIM_PREVISTA DATE,
    QTD_HR_PROJ INT NOT NULL,
    VLR_HR_PROJ DECIMAL(10, 2) NOT NULL,
    VLR_BASE_PROJ DECIMAL(10, 2) NOT NULL,
    VLR_DESCONTO_COMERCIAL DECIMAL(10, 2) NOT NULL,
    VLR_ACRESCIMO_PROJETO DECIMAL(10, 2) NOT NULL,
    VLR_FINAL_PROJETO DECIMAL(10, 2) NOT NULL,
    DT_INICIO_PROJ DATE,
    DT_FIM_PROJ DATE,
    VLR_FATURADO DECIMAL(10, 2) NOT NULL,
    SITUACAO_PROJ INT NOT NULL,
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME,
    FOREIGN KEY (CD_EMPRESA) REFERENCES PESSOA (CD_PESSOA),
    FOREIGN KEY (CD_CLIENTE) REFERENCES CLIENTE_EMPRESA (CD_CLIENTE),
    FOREIGN KEY (CD_RESP_PROJ) REFERENCES FUNCIONARIO_CLIENTE (CD_FUNCIONARIO),
    FOREIGN KEY (SITUACAO_PROJ) REFERENCES SITUACAO_PROJ (CD_SITUACAO)
);

-- Criação da tabela Atividade
CREATE TABLE ATIVIDADE (
    CD_ATIV INT PRIMARY KEY AUTO_INCREMENT,
    CD_PROJ INT NOT NULL,
    NOME_ATIV CHAR(40) NOT NULL,
    DT_INICIO_PREVISTA DATE NOT NULL,
    DT_FIM_PREVISTA DATE,
    QTD_HR_PREVISTA INT,
    QTD_HR INT,
    VLR_ATIV DECIMAL(10, 2),
    DT_INICIO_ATIV DATE,
    DT_FIM_ATIV DATE,
    SITUACAO_ATIV INT NOT NULL,
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME,
    FOREIGN KEY (CD_PROJ) REFERENCES PROJETO (CD_PROJ),
    FOREIGN KEY (SITUACAO_ATIV) REFERENCES SITUACAO_PROJ (CD_SITUACAO)
);

-- Criação da tabela para linkar as pessoas e atividades
CREATE TABLE PESSOA_ATIVIDADE (
    CD_PESSOA INT NOT NULL,
    CD_ATIV INT NOT NULL,
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE,
    QTD_HR INT,
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME,
    PRIMARY KEY (CD_PESSOA, CD_ATIV),
    FOREIGN KEY (CD_PESSOA) REFERENCES PESSOA (CD_PESSOA),
    FOREIGN KEY (CD_ATIV) REFERENCES ATIVIDADE (CD_ATIV)
);


-- Criação da tabela Histórico Perfil de Acesso
CREATE TABLE HIST_PERFIL_ACESSO (
    CD_PERFIL INT NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    NOME_PERFIL CHAR(20) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    PRIMARY KEY (CD_PERFIL, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Funções do Sistema
CREATE TABLE HIST_FUNCOES_SISTEMA (
    CD_FUNCAO INT NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    NOME_FUNCAO CHAR(30) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    PRIMARY KEY (CD_FUNCAO, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Funções do Perfil
CREATE TABLE HIST_FUNCOES_PERFIL (
    CD_PERFIL INT NOT NULL,
    CD_FUNCAO INT NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    PRIMARY KEY (CD_PERFIL, CD_FUNCAO, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Usuário
CREATE TABLE HIST_USUARIO (
    CD_USUARIO CHAR(8) NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    CD_PESSOA INT NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    SENHA CHAR(30) NOT NULL,
    DT_VALID DATE,
    PRIMARY KEY (CD_USUARIO, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Usuário por Empresa
CREATE TABLE HIST_USUARIO_EMPRESA (
    CD_USUARIO CHAR(8) NOT NULL,
    CD_EMPRESA INT NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    DT_VALID DATE,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    PRIMARY KEY (CD_USUARIO, CD_EMPRESA, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Cliente por Empresa
CREATE TABLE HIST_CLIENTE_EMPRESA (
    CD_CLIENTE INT NOT NULL,
    CD_EMPRESA INT NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    DT_INICIO DATE NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    PRIMARY KEY (CD_CLIENTE, CD_EMPRESA, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Funcionário Cliente
CREATE TABLE HIST_FUNCIONARIO_CLIENTE (
    CD_FUNCIONARIO INT NOT NULL,
    CD_CLIENTE INT NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    DT_INICIO DATE NOT NULL,
    CARGO_FUNCIONARIO INT NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    PRIMARY KEY (CD_FUNCIONARIO, CD_CLIENTE, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Cargo
CREATE TABLE HIST_CARGO (
    CD_CARGO INT NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    DESC_CARGO CHAR(30) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    PRIMARY KEY (CD_CARGO, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Situação Projeto
CREATE TABLE HIST_SITUACAO_PROJ (
    CD_SITUACAO INT NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    DESC_SITUACAO CHAR(20) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    PRIMARY KEY (CD_SITUACAO, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Pessoa
CREATE TABLE HIST_PESSOA (
    CD_PESSOA INT NOT NULL,
    DT_HR_ALTERACAO DATETIME NOT NULL,
    TP_PESSOA CHAR(1) NOT NULL COMMENT '(F / J)',
    NOME VARCHAR(40) NOT NULL,
    DT_NASC DATE,
    CPF_CNPJ DOUBLE,
    RG CHAR(12),
    EMAIL VARCHAR(60) NOT NULL,
    ATIVO TINYINT(1) NOT NULL COMMENT '(S / N)',
    CLIENTE TINYINT(1) COMMENT '(S / N)',
    EMPRESA TINYINT(1) COMMENT '(S / N)',
    IMAGEM VARCHAR(100),
    PRIMARY KEY (CD_PESSOA, DT_HR_ALTERACAO)
);

-- Criação da tabela Histórico Projeto
CREATE TABLE HIST_PROJETO (
    CD_PROJ INT NOT NULL,
    CD_EMPRESA INT NOT NULL,
    CD_CLIENTE INT NOT NULL,
    ID_PROJ_INTERNO CHAR(20) NOT NULL,
    ID_PROJ_CLIENTE CHAR(20),
    TP_PROJ CHAR(1) NOT NULL COMMENT '(A / P)',
    NOME_PROJ CHAR(40) NOT NULL,
    CD_RESP_PROJ INT NOT NULL,
    DT_INICIO_AVALIACAO DATE NOT NULL,
    DT_INICIO_NEGOCIACAO DATE,
    DT_INICIO_PREVISTA DATE NOT NULL,
    DT_FIM_PREVISTA DATE,
    QTD_HR_PROJ INT NOT NULL,
    VLR_HR_PROJ DECIMAL(10, 2) NOT NULL,
    VLR_BASE_PROJ DECIMAL(10, 2) NOT NULL,
    VLR_DESCONTO_COMERCIAL DECIMAL(10, 2) NOT NULL,
    VLR_ACRESCIMO_PROJETO DECIMAL(10, 2) NOT NULL,
    VLR_FINAL_PROJETO DECIMAL(10, 2) NOT NULL,
    DT_INICIO_PROJ DATE NOT NULL,
    DT_FIM_PROJ DATE,
    VLR_FATURADO DECIMAL(10, 2) NOT NULL,
    SITUACAO_PROJ INT NOT NULL,
    USU_INCLUSAO CHAR(8) NOT NULL,
    DT_HR_INCLUSAO DATETIME DEFAULT NOW(),
    USU_ALTERACAO CHAR(8),
    DT_HR_ALTERACAO DATETIME,
    PRIMARY KEY (CD_PROJ, DT_HR_ALTERACAO)
);